### ISSUE TITLE
PFLAU data horizontal and vertical distance sometimes not set

### ISSUE THREAD

**Issue by FlyingBird22** [CazYokoyama/SoftRF#1]
```    
    $PFLAA,0,-2414,-5178,-1036,2,DD988A!FLR_DD988A,0,,0,0.0,1*6C
    $PFLAA,0,-2410,-5170,-1040,2,DD9689!FLR_DD9689,0,,0,0.1,1*60
    $PFLAA,0,-2420,-5191,-1037,2,DD92F1!FLR_DD92F1,0,,0,0.1,1*6C
    $PFLAA,0,-2427,-5205,-1039,2,DDAB50!FLR_DDAB50,0,,0,0.1,1*6B
    $PFLAA,0,-2514,-5391,-1034,2,D00547!FLR_D00547,0,,0,0.0,1*6A
    $PFLAA,0,-2439,-5231,-1040,2,DDA90C!FLR_DDA90C,135,,0,0.1,1*6A
    $PFLAA,0,-1959,-4401,-701,2,DDA9CC!FLR_DDA9CC,87,,24,4.1,1*5F
    $PFLAA,0,-2312,-5194,-1036,2,DD913E!FLR_DD913E,236,,0,0.1,1*69

    $PFLAU,8,1,2,1,0,-125,2,0,2147483647,000000*67
```

**Comment by FlyingBird22** [comment]
The problem is in Linar's code since 10th of August and affects everything that is based on that commit.
(At first, by accident, I was searching the bug in an older code version and therefore couldn't find the bug.)

**Comment by CazYokoyama** [comment]
38b1a81e was a temporary test fix. I pushed the final fix, 1.0-rc8-24640a69 and keep corresponding firmware binary in http://www.caztech.com/glider/softrf/prime-mk2/firmware/. Could you test and report if it has the symptom you report?

**Comment by FlyingBird22** [comment]
@CazYokoyama Hi Caz, tested 38b1a81e last days and fixed the problem. Is there a way I can commit my branch to your repo or ask you for a pull request? I'm able to compile by myself through Arduino Platform and Visual Studio Code and directly flash the board. I also have a new binary.

**Comment by FlyingBird22** [comment]
**See:**           [**FlyingBird22/SoftRF/issues/2**](https://github.com/FlyingBird22/SoftRF/issues/2)
**Solved at:**  [**FlyingBird22/SoftRF/tree/1.0-rc8-Dave-1**](https://github.com/FlyingBird22/SoftRF/tree/1.0-rc8-Dave-1)

**Comment by CazYokoyama** [comment]
I am confused. You calculates distance in 3D, i.e. include vertical separation.
However, altitude difference is much important than horizontal separation. Therefore, I prefer Linar's code.

To ignore static object, adding (fop->speed > 0) to (abs(alt_diff) < VERTICAL_SEPARATION). You changes whole "if".

**Comment by FlyingBird22** [comment]
1.) This issue #1 came into Linar's repo by 10th August:  [**better NMEA compliance to FTD-12**](https://github.com/lyusupov/SoftRF/commit/0a90d833c55c7747396893aaeceb77fd4d81af92)
If you want to have this _second-order condition_ **`abs(alt_diff) < VERTICAL_VISIBILITY_RANGE`** you have to put it at the front of the method, not to produce any **PFLAA** sentences. It is completely missplaced here.
2.) The (good) idea at Linar's code is to get every **fo** that has been received by transmission and set it to **_traffic info_**, means **alarm level = 0** (**TRAFFIC_ALARM_NONE**). But at his code it is possible (and I've seen it in my logging) to get **PFLAU**s with TRAFFIC_ALARM_NONE even you have more dangerous **fo**s arround.
3.) Non-airborn aircrafts beeing static have a noise in there position data and sometimes generate a small ghost speed (seen in log file).
4.) If you look closer into my second adaption at [**FlyingBird22/SoftRF/tree/1.0-rc8-Dave-2**](https://github.com/FlyingBird22/SoftRF/tree/1.0-rc8-Dave-2) you will understand the idea behind it.
5.) At my location I watched (and I'm focused on) not only gliders but also helicopters and paragliders with vertical movement and also beeing static at launch position on top of mountain.
6.) Worst case at Linar's code is a **fo** standing on ground 299 meters below and you are flying around above. This **fo** will overwrite the dangerous **fo** at the same altitude level coming towards you and you will not see it at PFLAU.

**Comment by FlyingBird22** [comment]
![alarm zones](https://user-images.githubusercontent.com/69727555/95187755-cc2a1e80-07cb-11eb-855c-a8a871eb4a62.jpg)
Think about that and you will see, that my algorithm is much better than Linar's.
Don't forget that I've taken **alarm_level** into account to get **PFLAU** data.
